### ISSUE TITLE
Add asterisks to all required fields on the registration form

### ISSUE THREAD

**Issue by shhavel** [outwalk/offers#3]
Registration form: http://offers.kiev.ua/users/sign_up?locale=uk

Possible solution:
add CSS class `required` for HTML tag `label`,
then apply class to all required fields.

``` css
label.required:before {
  content:" *";
  color: rgba(255,48,0,0.87);
  font-weight: bold;
  font-size: 100%;
  margin-right: 5px;
}
```

Links:
http://stackoverflow.com/questions/23343414/bootstrap-3-add-an-asterisk-to-the-input-on-the-same-row
http://stackoverflow.com/questions/23141854/adding-asterisk-to-required-fields-in-bootstrap-3
